// Symbolic dry-run references only — never a real UUID. Real UUIDs are
// generated by the database itself at real-ingestion time (gen_random_uuid()),
// never fabricated here.
export { slugify } from "../../plant-benchmark/src/cache.js";

function toRefSegment(name) {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/(^_|_$)/g, "");
}

export function taxonRef(canonicalName) {
  return toRefSegment(canonicalName);
}

export function catalogRef({ taxonSlug, cultivarName = null }) {
  return cultivarName ? `${taxonSlug}_${toRefSegment(cultivarName)}` : `${taxonSlug}_species`;
}

export function sourceRecordRef({ catalogRef: catRef, provider }) {
  return `${catRef}:${provider}:current`;
}

export function observationRef({ catalogRef: catRef, provider, trait, index = 0 }) {
  return index > 0 ? `${catRef}:${provider}:${trait}:${index}` : `${catRef}:${provider}:${trait}`;
}
