#!/usr/bin/env node
// LOCAL TEST ONLY adapter: compiles a transaction plan and emits a SQL
// script that inserts it into a DISPOSABLE local PostgreSQL database
// inside a single transaction, asserts the expected state, then rolls
// back. This is not part of the shipped ingestion tool and is never run
// against Supabase — no service_role key, no connection string, no
// Supabase client anywhere in this file.
//
// The UUIDs generated here to stand in for symbolic refs (taxon_ref,
// catalog_ref, source_record_ref, observation_ref) are LOCAL_TEST_ONLY:
// generated fresh via crypto.randomUUID() on every run, kept only in this
// script's memory, and never written to the plan JSON or anywhere else.
// Usage: node localPostgresAdapter.mjs <bundle.json> > /tmp/plan.sql

import { readFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { compileTransactionPlan } from "../../src/plan/compiler.js";

function sqlString(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlBool(value) {
  if (value === null || value === undefined) return "NULL";
  return value ? "true" : "false";
}

function sqlNumber(value) {
  if (value === null || value === undefined) return "NULL";
  return String(value);
}

function sqlJsonb(value) {
  if (value === null || value === undefined) return "NULL";
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function sqlTextArray(value) {
  if (value === null || value === undefined) return "NULL";
  return `ARRAY[${value.map((v) => sqlString(v)).join(",")}]::text[]`;
}

function sqlSmallintArray(value) {
  if (value === null || value === undefined) return "NULL";
  return `ARRAY[${value.map((v) => sqlNumber(v)).join(",")}]::smallint[]`;
}

const bundlePath = process.argv[2];
if (!bundlePath) {
  console.error("usage: node localPostgresAdapter.mjs <bundle.json>");
  process.exit(1);
}

const bundle = JSON.parse(readFileSync(bundlePath, "utf8"));
const result = compileTransactionPlan(bundle);
if (!result.ok) {
  console.error("Compilation failed — will not generate SQL for an invalid plan:");
  for (const e of result.errors) console.error(`  [${e.code}] ${e.message}`);
  process.exit(1);
}
const plan = result.plan;

// LOCAL_TEST_ONLY ref -> UUID maps. Never persisted, never sent anywhere.
const taxonIdByRef = new Map(plan.taxa.map((t) => [t.taxon_ref, randomUUID()]));
const catalogIdByRef = new Map(plan.catalog_entries.map((c) => [c.catalog_ref, randomUUID()]));
const sourceRecordIdByRef = new Map(plan.source_records.map((s) => [s.source_record_ref, randomUUID()]));
const observationIdByRef = new Map(plan.trait_observations.map((o) => [o.observation_ref, randomUUID()]));

const lines = [];
lines.push("-- LOCAL TEST ONLY — generated by localPostgresAdapter.mjs. Never run against Supabase.");
lines.push("begin;");

// 1. plant_taxa
for (const t of plan.taxa) {
  const id = taxonIdByRef.get(t.taxon_ref);
  lines.push(
    `insert into public.plant_taxa (id, rank, genus, species, infraspecific_epithet, canonical_name, scientific_name_full, family, taxonomic_status, wcvp_taxon_id) values (` +
      `${sqlString(id)}, ${sqlString(t.rank)}, ${sqlString(t.genus)}, ${sqlString(t.species)}, ${sqlString(t.infraspecific_epithet)}, ${sqlString(t.canonical_name)}, ${sqlString(t.scientific_name_full)}, ${sqlString(t.family)}, ${sqlString(t.taxonomic_status)}, ${sqlString(t.wcvp_taxon_id)});`
  );
}

// 2. plant_taxon_names
for (const n of plan.taxon_names) {
  const taxonId = taxonIdByRef.get(n.taxon_ref);
  lines.push(
    `insert into public.plant_taxon_names (id, taxon_id, name, normalized_name, name_type, source_taxon_id) values (` +
      `${sqlString(randomUUID())}, ${sqlString(taxonId)}, ${sqlString(n.name)}, ${sqlString(n.normalized_name)}, ${sqlString(n.name_type)}, ${sqlString(n.source_taxon_id)});`
  );
}

// 3. plant_catalog — species before cultivar (compiler already orders this way).
for (const c of plan.catalog_entries) {
  const id = catalogIdByRef.get(c.catalog_ref);
  const taxonId = taxonIdByRef.get(c.taxon_ref);
  const parentId = c.parent_catalog_ref ? catalogIdByRef.get(c.parent_catalog_ref) : null;
  lines.push(
    `insert into public.plant_catalog (id, taxon_id, parent_catalog_id, entry_type, cultivar_name, display_name, common_name, slug, publication_status, review_status, published_at, plant_type, growth_form, height_min_cm, height_max_cm, spread_max_cm, sun, hardiness_min_rank, hardiness_max_rank, evergreen, water_need, container_suitable, edible, flowering_months) values (` +
      `${sqlString(id)}, ${sqlString(taxonId)}, ${sqlString(parentId)}, ${sqlString(c.entry_type)}, ${sqlString(c.cultivar_name)}, ${sqlString(c.display_name)}, ${sqlString(c.common_name)}, ${sqlString(c.slug)}, ${sqlString(c.publication_status)}, ${sqlString(c.review_status)}, ${sqlString(c.published_at)}, ` +
      `${sqlString(c.plant_type)}, ${sqlString(c.growth_form)}, ${sqlNumber(c.height_min_cm)}, ${sqlNumber(c.height_max_cm)}, ${sqlNumber(c.spread_max_cm)}, ${sqlTextArray(c.sun)}, ${sqlNumber(c.hardiness_min_rank)}, ${sqlNumber(c.hardiness_max_rank)}, ${sqlBool(c.evergreen)}, ${sqlString(c.water_need)}, ${sqlBool(c.container_suitable)}, ${sqlBool(c.edible)}, ${sqlSmallintArray(c.flowering_months)});`
  );
}

// 4. plant_source_records
for (const s of plan.source_records) {
  const id = sourceRecordIdByRef.get(s.source_record_ref);
  const catalogId = catalogIdByRef.get(s.catalog_ref);
  lines.push(
    `insert into public.plant_source_records (id, plant_catalog_id, provider, provider_record_id, provider_name, provider_status, selection_reason, taxonomy_match_type, candidate_count, retrieved_at, source_url, metadata) values (` +
      `${sqlString(id)}, ${sqlString(catalogId)}, ${sqlString(s.provider)}, ${sqlString(s.provider_record_id)}, ${sqlString(s.provider_name)}, ${sqlString(s.provider_status)}, ${sqlString(s.selection_reason)}, ${sqlString(s.taxonomy_match_type)}, ${sqlNumber(s.candidate_count)}, ${sqlString(s.retrieved_at)}, ${sqlString(s.source_url)}, ${sqlJsonb(s.metadata)});`
  );
}

// 5. plant_trait_observations
for (const o of plan.trait_observations) {
  const id = observationIdByRef.get(o.observation_ref);
  const catalogId = catalogIdByRef.get(o.catalog_ref);
  const sourceRecordId = o.provider === "editorial" ? null : sourceRecordIdByRef.get(o.source_record_ref);
  lines.push(
    `insert into public.plant_trait_observations (id, plant_catalog_id, trait, provider, field_path, raw_value, raw_unit, normalized_value, normalized_unit, plant_source_record_id, source_url, attribution, license, source_retrieved_at, uncertain, source_scope, review_status) values (` +
      `${sqlString(id)}, ${sqlString(catalogId)}, ${sqlString(o.trait)}, ${sqlString(o.provider)}, ${sqlString(o.field_path)}, ${sqlJsonb(o.raw_value)}, ${sqlString(o.raw_unit)}, ${sqlJsonb(o.normalized_value)}, ${sqlString(o.normalized_unit)}, ${sqlString(sourceRecordId)}, ${sqlString(o.source_url)}, ${sqlString(o.attribution)}, ${sqlString(o.license)}, ${sqlString(o.source_retrieved_at)}, ${sqlBool(o.uncertain)}, ${sqlString(o.source_scope)}, ${sqlString(o.review_status)});`
  );
}

// 6. plant_trait_selections
for (const s of plan.trait_selections) {
  const catalogId = catalogIdByRef.get(s.catalog_ref);
  const observationId = observationIdByRef.get(s.selected_observation_ref);
  lines.push(
    `insert into public.plant_trait_selections (id, plant_catalog_id, trait, selected_observation_id, decision_method, decided_by, note) values (` +
      `${sqlString(randomUUID())}, ${sqlString(catalogId)}, ${sqlString(s.trait)}, ${sqlString(observationId)}, ${sqlString(s.decision_method)}, ${sqlString(s.decided_by)}, ${sqlString(s.note)});`
  );
}

lines.push("");
lines.push("\\echo == row counts inside the transaction ==");
lines.push("select 'plant_taxa' as t, count(*) from public.plant_taxa");
lines.push("union all select 'plant_taxon_names', count(*) from public.plant_taxon_names");
lines.push("union all select 'plant_catalog', count(*) from public.plant_catalog");
lines.push("union all select 'plant_source_records', count(*) from public.plant_source_records");
lines.push("union all select 'plant_trait_observations', count(*) from public.plant_trait_observations");
lines.push("union all select 'plant_trait_selections', count(*) from public.plant_trait_selections;");

lines.push("");
lines.push("\\echo == Acer species row ==");
lines.push(`select entry_type, publication_status, review_status, plant_type, height_min_cm, height_max_cm, sun, hardiness_min_rank, hardiness_max_rank from public.plant_catalog where id = '${catalogIdByRef.get("acer_palmatum_species")}';`);

lines.push("\\echo == Bloodgood row + parent check ==");
lines.push(
  `select c.entry_type, c.publication_status, c.review_status, c.plant_type, c.height_min_cm, c.height_max_cm, c.sun, c.hardiness_min_rank, c.hardiness_max_rank, p.entry_type as parent_entry_type ` +
    `from public.plant_catalog c join public.plant_catalog p on p.id = c.parent_catalog_id where c.id = '${catalogIdByRef.get("acer_palmatum_bloodgood")}';`
);

lines.push("\\echo == Trefle Bloodgood source record + observation count ==");
lines.push(`select provider_status from public.plant_source_records where id = '${sourceRecordIdByRef.get("acer_palmatum_bloodgood:trefle:current")}';`);
lines.push(`select count(*) as trefle_bloodgood_observations from public.plant_trait_observations where plant_catalog_id = '${catalogIdByRef.get("acer_palmatum_bloodgood")}' and provider = 'trefle';`);

lines.push("\\echo == every selection: FK + same catalog/trait + catalog typed value coherence ==");
lines.push(
  `select sel.trait, sel.plant_catalog_id = obs.plant_catalog_id as same_catalog, sel.trait = obs.trait as same_trait ` +
    `from public.plant_trait_selections sel join public.plant_trait_observations obs on obs.id = sel.selected_observation_id;`
);

lines.push("");
lines.push("rollback;");
lines.push("\\echo == row counts AFTER rollback (must all be 0) ==");
lines.push("select 'plant_taxa' as t, count(*) from public.plant_taxa");
lines.push("union all select 'plant_taxon_names', count(*) from public.plant_taxon_names");
lines.push("union all select 'plant_catalog', count(*) from public.plant_catalog");
lines.push("union all select 'plant_source_records', count(*) from public.plant_source_records");
lines.push("union all select 'plant_trait_observations', count(*) from public.plant_trait_observations");
lines.push("union all select 'plant_trait_selections', count(*) from public.plant_trait_selections;");

process.stdout.write(lines.join("\n") + "\n");
