-- Common-name (vernacular name) architecture v1.
--
-- Follow-up to the search-engine audit: search_published_plants already
-- covers scientific names (display_name/cultivar_name) and taxonomic
-- synonyms (plant_taxon_names), but 0/22 published plant_catalog rows have
-- a common_name — and that single, untyped, nullable text field has no
-- room for "French AND English", nor for more than one name per plant.
-- This migration adds a dedicated, normalized table instead of overloading
-- plant_catalog.common_name — which is left completely untouched (no
-- column dropped, renamed, backfilled, or repurposed) so nothing reading
-- it today changes behavior.
--
-- NOT APPLIED LIVE THIS ROUND (per instruction) — prepared and validated
-- via a rolled-back transaction against the live project only. No common
-- name data is inserted by this file; it is schema + search wiring only.
--
-- =============================================================================
-- 1. immutable_unaccent(text) — a real IMMUTABLE wrapper around the
--    `unaccent` extension's own function (which is STABLE, and therefore
--    cannot back a generated column or a functional index). Pinning the
--    dictionary explicitly (rather than relying on the session's default
--    search_path resolving `unaccent`) is what makes the IMMUTABLE
--    contract honest — the same input always normalizes to the same
--    output, regardless of session state. Reused below both for
--    plant_common_names.normalized_name (a generated column — accurate,
--    automatic duplicate protection, never trusts a caller to have
--    normalized correctly) and inside the updated search_published_plants
--    RPC (replacing its 3 prior direct extensions.unaccent(...) calls, so
--    every accent-fold in this codebase now goes through one function).
-- =============================================================================
create or replace function public.immutable_unaccent(text)
returns text
language sql
immutable
parallel safe
as $$
  select extensions.unaccent('extensions.unaccent'::regdictionary, $1)
$$;

-- =============================================================================
-- 2. plant_common_names — one row per (taxon, locale, name). Vernacular
--    names ONLY: never a trade name, never a cultivar name (plant_catalog
--    already owns cultivar_name) — that distinction is an editorial-review
--    policy, not something a CHECK constraint can safely enforce (no
--    reliable structural signal separates "Lavande officinale" from a made
--    -up trade name), so it is enforced at curation time, the same way
--    curation_method="restricted_source_paraphrase" is schema-ready but
--    editorially gated in scripts/plant-ingestion/src/editorial/.
--
--    taxon_id (not plant_catalog_id): a common name is a property of the
--    TAXON, same as plant_taxon_names — "lavande" applies to the species
--    Lavandula angustifolia, not to one specific catalog/cultivar row, so
--    it is never duplicated per cultivar entry sharing that taxon.
-- =============================================================================
create table public.plant_common_names (
  id uuid primary key default gen_random_uuid(),
  taxon_id uuid not null references public.plant_taxa (id) on delete cascade,
  name text not null,
  -- Generated, not caller-supplied (unlike plant_taxon_names.normalized_name,
  -- which predates this table and is lowercase-only — scientific names are
  -- effectively always ASCII, so that was never a gap there). Vernacular
  -- names are frequently accented ("Érable", "fougère"), so accent-aware
  -- normalization here is generated by the DB itself: duplicate protection
  -- (the unique constraint below) can never be defeated by a caller simply
  -- forgetting to fold accents/case before insert.
  normalized_name text generated always as (lower(public.immutable_unaccent(name))) stored,
  locale text not null,
  is_preferred boolean not null default false,

  -- Provenance — same vocabulary as plant_trait_observations' editorial
  -- columns (supabase/migrations/20260902100000_add_editorial_provenance_v1.sql),
  -- reused deliberately for consistency rather than inventing a parallel
  -- "source_type/source_name" shape: source_url/source_title/source_publisher
  -- identify the source actually consulted, `license` is that SOURCE's own
  -- license/status (never our synthesis — there is no curation_license
  -- twin here, unlike trait observations: a name is transcribed, not
  -- synthesized from multiple numeric facts), curation_method records how
  -- it was obtained, curated_by/reviewed_by/reviewed_at record who vouched
  -- for it and when.
  source_url text null,
  source_title text null,
  source_publisher text null,
  license text null,
  curation_method text not null,
  curated_by uuid null references auth.users (id) on delete set null,
  reviewed_by uuid null references auth.users (id) on delete set null,
  reviewed_at timestamptz null,

  created_at timestamptz not null default now(),
  -- Unlike plant_taxa/plant_catalog/plant_taxon_names (whose updated_at,
  -- where present at all, is a vestigial insert-time default with no
  -- trigger — confirmed: no ingestion code ever writes it), a common name
  -- IS expected to be corrected/re-reviewed after insert (is_preferred
  -- flipped, a better source found) — closer to profiles/garden_zones
  -- (user-editable rows) than to the append-mostly catalog tables, so it
  -- gets the real set_updated_at() trigger those already use.
  updated_at timestamptz not null default now(),

  constraint plant_common_names_locale_check
    check (locale in ('fr', 'en')),
  constraint plant_common_names_curation_method_check
    check (curation_method in ('expert_knowledge', 'open_source_synthesis', 'restricted_source_paraphrase')),
  constraint plant_common_names_name_not_blank_check
    check (btrim(name) <> ''),
  -- No invented/unsourced names: expert_knowledge is the only method
  -- allowed to skip source_url (a named curator personally vouching, no
  -- written source to cite) — anything claiming an external source must
  -- actually carry one. Mirrors the editorial pipeline's own discipline
  -- (buildEditorialObservation.js never fabricates source fields either).
  constraint plant_common_names_source_required_check
    check (curation_method = 'expert_knowledge' or source_url is not null),
  -- Duplicate protection: at most one row per (taxon, locale, normalized
  -- name) — "Lavande officinale" and "lavande officinale" collide, by
  -- design (normalized_name is accent+case-folded).
  constraint plant_common_names_taxon_locale_normalized_name_unique
    unique (taxon_id, locale, normalized_name)
);

create index plant_common_names_taxon_id_idx on public.plant_common_names (taxon_id);
create index plant_common_names_locale_idx on public.plant_common_names (locale);
create index plant_common_names_normalized_name_idx on public.plant_common_names (normalized_name);

-- At most one preferred name per (taxon, locale) — the FR/EN display
-- architecture (see report) reads this row to show a single canonical
-- vernacular name per active UI locale.
create unique index plant_common_names_one_preferred_per_taxon_locale
  on public.plant_common_names (taxon_id, locale)
  where is_preferred;

drop trigger if exists set_plant_common_names_updated_at on public.plant_common_names;
create trigger set_plant_common_names_updated_at
before update on public.plant_common_names
for each row execute function public.set_updated_at();

-- =============================================================================
-- 3. RLS — same policy shape as plant_taxon_names (backbone reference data,
--    safe to expose in full: a common name is a botanical/linguistic fact
--    about a taxon, not itself a draft catalog entry's existence — same
--    reasoning already applied to plant_taxa/plant_taxon_names, which are
--    likewise unconditionally public regardless of any catalog entry's
--    publication_status). Writes stay service_role-only, same as every
--    other table in this schema — no anon/authenticated write path exists
--    or is added.
-- =============================================================================
alter table public.plant_common_names enable row level security;

create policy plant_common_names_public_select
  on public.plant_common_names
  for select
  to anon, authenticated
  using (true);

revoke all on public.plant_common_names from public, anon, authenticated;
grant select on public.plant_common_names to anon, authenticated;
grant select, insert, update, delete on public.plant_common_names to service_role;

comment on table public.plant_common_names is
  'Vernacular/common names per taxon and locale (fr/en only for now). Never trade names or cultivar names (plant_catalog.cultivar_name owns those) — enforced editorially, not by CHECK. See search_published_plants for how this feeds Plant Finder search, and the FR/EN display note in the round report for how a UI would later read is_preferred per locale.';

-- =============================================================================
-- 4. search_published_plants — extended to also match plant_common_names
--    (any locale, not just the UI's active one: a French speaker typing
--    an English name someone shared, or vice versa, should still find the
--    plant). Every other clause — published-only, plant_type/sun/height
--    filters, total-before-pagination, ordering, SECURITY INVOKER — is
--    byte-for-byte unchanged from
--    supabase/migrations/20260911090000_add_plant_finder_search_rpc.sql;
--    only the matching predicate gained one more EXISTS branch, and every
--    extensions.unaccent(...) call now goes through immutable_unaccent()
--    instead (same normalization, now shared with the generated column
--    above rather than duplicated). Signature is unchanged — no client
--    code (lib/plantFinderApi.js) needs to change for this.
-- =============================================================================
create or replace function public.search_published_plants(
  search_query text default null,
  plant_type_filter text default null,
  sun_filter text[] default null,
  height_min numeric default null,
  height_max numeric default null,
  result_limit integer default 20,
  result_offset integer default 0
)
returns jsonb
language sql
stable
security invoker
set search_path = public, extensions
as $$
  with normalized as (
    select case
      when search_query is null or btrim(search_query) = '' then null
      else lower(public.immutable_unaccent(btrim(search_query)))
    end as q
  ),
  escaped as (
    select case
      when q is null then null
      else replace(replace(replace(q, '\', '\\'), '%', '\%'), '_', '\_')
    end as q_escaped
    from normalized
  ),
  matched as (
    select
      pc.id, pc.slug, pc.entry_type, pc.cultivar_name, pc.display_name, pc.common_name,
      pc.plant_type, pc.growth_form, pc.height_min_cm, pc.height_max_cm, pc.spread_max_cm,
      pc.sun, pc.evergreen, pc.water_need, pc.container_suitable, pc.edible, pc.flowering_months,
      pc.image_url, pc.image_alt, pc.image_author, pc.image_license, pc.image_source_url,
      pt.canonical_name, pt.family, pt.genus
    from public.plant_catalog pc
    join public.plant_taxa pt on pt.id = pc.taxon_id
    cross join escaped
    where pc.publication_status = 'published'
      and (
        escaped.q_escaped is null
        or lower(public.immutable_unaccent(pc.display_name)) like '%' || escaped.q_escaped || '%' escape '\'
        or (pc.common_name is not null and lower(public.immutable_unaccent(pc.common_name)) like '%' || escaped.q_escaped || '%' escape '\')
        or (pc.cultivar_name is not null and lower(public.immutable_unaccent(pc.cultivar_name)) like '%' || escaped.q_escaped || '%' escape '\')
        or exists (
          select 1 from public.plant_taxon_names ptn
          where ptn.taxon_id = pc.taxon_id
            and lower(public.immutable_unaccent(ptn.name)) like '%' || escaped.q_escaped || '%' escape '\'
        )
        or exists (
          select 1 from public.plant_common_names pcn
          where pcn.taxon_id = pc.taxon_id
            and pcn.normalized_name like '%' || escaped.q_escaped || '%' escape '\'
        )
      )
      and (plant_type_filter is null or pc.plant_type = plant_type_filter)
      and (sun_filter is null or pc.sun && sun_filter)
      and (height_min is null or pc.height_max_cm > height_min)
      and (height_max is null or pc.height_max_cm <= height_max)
  )
  select jsonb_build_object(
    'total', (select count(*) from matched),
    'rows', coalesce(
      (
        select jsonb_agg(to_jsonb(page) order by page.display_name, page.id)
        from (
          select * from matched
          order by display_name asc, id asc
          limit result_limit offset result_offset
        ) page
      ),
      '[]'::jsonb
    )
  );
$$;

comment on function public.search_published_plants(text, text, text[], numeric, numeric, integer, integer) is
  'Plant Finder search: published plant_catalog rows matched by display_name/common_name/cultivar_name, any plant_taxon_names synonym, or any plant_common_names vernacular name (fr or en) for the same taxon — case- and accent-insensitive throughout. Returns {total, rows} in one round trip. See lib/plantFinderApi.js.';

revoke all on function public.search_published_plants(text, text, text[], numeric, numeric, integer, integer) from public;
grant execute on function public.search_published_plants(text, text, text[], numeric, numeric, integer, integer) to anon, authenticated;
